### ISSUE TITLE
FreedomLink Email Automation (Big Picture Story)

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands#228]
### Overview
Tiny Hands has donors that are being sent emails about stories from the interceptions that are saved on the Dream Suite (IRFs). Each month these donors are being sent a story that is currently being generated by Jon Hudlow's excel sheet. The excel sheet converts data from an interception into a story based on a complex equation, the text of which would be sent in the body of these emails. These stories can be categorized based on the type of interception that was made, which will be used to ensure donors receive a variety of stories. Before sending an email, we should allow a user at the Tiny Hands home base to check the stories and make a mark in a column to approve that the story is ready to be sent. Stories are currently being sent using Adobe Spark (see Andrew's example below) so we will need to create a comparable PDF with the stories placed over pictures.

### Sub-Stories
- [ ] Create tables for backend 
- [ ] Pull current approved stories, use algorithm to match story up with donor, and send PDF (see below) to their email
- [ ] Create PDFs from stories as alternative to Adobe Spark 
- [ ] Recreate functionality from Jon's Google sheet in a service that will generate stories on its own

**Comment by andrewfennig** [comment]
Here is the current solution. THI Staff make a separate Adobe Spark page for each story and email a link to the donor. The site is up from Friday to Monday and then is taken down. Here is an example page:

https://spark.adobe.com/page/7EqT0wwbNWBnc/

**Comment by amunn33** [comment]
Possible options for PDF creation:
- ImageMagick: https://www.imagemagick.org/script/index.php
- ReportLab: https://www.blog.pythonlibrary.org/2010/03/08/a-simple-step-by-step-reportlab-tutorial/
- ReportLab Link 2: https://www.reportlab.com/docs/reportlab-userguide.pdf

**Comment by amunn33** [comment]
Here is the current Google Sheet that is being used to create these stories

https://docs.google.com/a/tinyhandsintl.org/spreadsheets/d/14HIaCeqkUfrdq3DGncv6wKkOMF0oHuVQuj9gpURb6iI/edit?usp=sharing

**Comment by jsouthwo** [comment]
@amunn33 The Google Doc is locked. I've requested access.

**Comment by amunn33** [comment]
Sorry about that I gave you access but it should also be available to anyone with the link now

**Comment by amunn33** [comment]
[This has been moved into its own repo](https://github.com/Tiny-Hands/freedom-link/issues)

**Comment by amunn33** [comment]
[This has been moved into its own repo](https://github.com/Tiny-Hands/freedom-link/issues)
